<?php

const WEEKLY_PAYMENT_ID = 1;

const OPEN_LOAN_STATUS_ID = 6;
const CLOSED_LOAN_STATUS_ID = 7;
const DEFAULT_LOAN_STATUS_ID = 8;
const APPLIED_LOAN_STATUS_ID = 9;
const CASH_PAYMENT_TYPE_ID = 10;
const CC_PAYMENT_TYPE_ID = 12;
const REJECT_LOAN_STATUS_ID = 13;

const ARRANGEMENT_FEE_HEAD_ID = 14;
const LATE_PENALITY_FEE_HEAD_ID = 15;
const EMI_HEAD_ID = 16;
const EARLY_LOAN_CLOSURE_HEAD_ID = 17;
